server:
  port: 8761

eureka:
  instance:
      preferIpAddress: true
      lease-expiration-duration-in-seconds: 1
      lease-renewal-interval-in-seconds: 10
      instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
